# This file was generated by GoReleaser. DO NOT EDIT.
cask "boursocli" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "07ace7f17fe11f8eabcad95c87db2a9383e330c71ebbc92654e51810cf1ec123"
      url "https://github.com/ThomasMarcelin754/boursocli/releases/download/v#{version}/boursocli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "adaf47adb56f651292e2db00c00209dd4782f2510fe00ed6c76badd26ac56e73"
      url "https://github.com/ThomasMarcelin754/boursocli/releases/download/v#{version}/boursocli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f0b3a8f7e3b73d9bdd85ed133af40e56b6cac2f5f8fd59e058825eef92664de9"
      url "https://github.com/ThomasMarcelin754/boursocli/releases/download/v#{version}/boursocli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "605d89c22751338631f430f0455e7899655f5377a57a899c9a45f42f7ea4194a"
      url "https://github.com/ThomasMarcelin754/boursocli/releases/download/v#{version}/boursocli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "boursocli"
  desc "Agent-first CLI for a personal BoursoBank account"
  homepage "https://github.com/thomasmarcelin754/boursocli"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "node",
    ]

  binary "boursocli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boursocli"]
    end
  end

  # No zap stanza required

end
