# This file was generated by GoReleaser. DO NOT EDIT.
cask "sncf" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "6f6e7a3d0dd23dbdb379a3213428ac65f022e5773815018dc424c37feb23f5cd"
      url "https://github.com/ThomasMarcelin754/clisncf/releases/download/v#{version}/sncf_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ThomasMarcelin754/clisncf"
    end
    on_arm do
      sha256 "7797ff301866f9679128c2036485cecae1719e7dea1f6c27516774e23f5883b9"
      url "https://github.com/ThomasMarcelin754/clisncf/releases/download/v#{version}/sncf_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ThomasMarcelin754/clisncf"
    end
  end

  on_linux do
    on_intel do
      sha256 "7b3b6c697f9a3604c4d40aa71fe2d736d1bab8b188ab926f5cb9f0c56dd568d0"
      url "https://github.com/ThomasMarcelin754/clisncf/releases/download/v#{version}/sncf_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ThomasMarcelin754/clisncf"
    end
    on_arm do
      sha256 "df32849321ad10b717ac9b0402a71038d47e5b0ef9412ebb20ec855e70b0da2b"
      url "https://github.com/ThomasMarcelin754/clisncf/releases/download/v#{version}/sncf_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ThomasMarcelin754/clisncf"
    end
  end

  name "sncf"
  desc "CLI for SNCF Connect — search trains, book tickets, manage your account"
  homepage "https://github.com/ThomasMarcelin754/clisncf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sncf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sncf"]
    end
  end

  # No zap stanza required

end
