# This file was generated by GoReleaser. DO NOT EDIT.
cask "sncfcli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "f703c0916326b12fbe19130e0f2a356f60d900a0847adde0ee4c1e895ac6ce0e"
      url "https://github.com/ThomasMarcelin754/clisncf/releases/download/v#{version}/sncfcli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ThomasMarcelin754/clisncf"
    end
    on_arm do
      sha256 "02b4fa43e6f7f38589c62ed007c56b33bd58eaeeb6aea1bd6ae1a3d41255b818"
      url "https://github.com/ThomasMarcelin754/clisncf/releases/download/v#{version}/sncfcli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ThomasMarcelin754/clisncf"
    end
  end

  on_linux do
    on_intel do
      sha256 "4a3a92339b947dd985c2fddd9a017a2dab7962fc5d18e4a0accbce4edc2cf07b"
      url "https://github.com/ThomasMarcelin754/clisncf/releases/download/v#{version}/sncfcli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ThomasMarcelin754/clisncf"
    end
    on_arm do
      sha256 "13612a4e8d058061de11c53b514e8fdb847d3669ae70173569273d2754c683dc"
      url "https://github.com/ThomasMarcelin754/clisncf/releases/download/v#{version}/sncfcli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ThomasMarcelin754/clisncf"
    end
  end

  name "sncfcli"
  desc "CLI for SNCF Connect — search trains, book tickets, manage your account"
  homepage "https://github.com/ThomasMarcelin754/clisncf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sncfcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sncfcli"]
    end
  end

  # No zap stanza required

end
